spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.application.name=SpringBoot_REST_API_Blueprints

spring.datasource.url=jdbc:postgresql://localhost:5432/blueprints
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

springdoc.swagger-ui.path=/swagger-ui.html

server.port=8082
